/**
 * Static dropdown options for form components
 * Centralized location for reusable select options
 */

import type { SelectOption } from "@/components/form"

// Gender options for profile forms
export const genderOptions: SelectOption[] = [
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
  { value: "other", label: "Other" },
  { value: "prefer_not_to_say", label: "Prefer not to say" }
]

// Country options — complete ISO 3166-1 alpha-2 list, sorted by name.
// `value` is the 2-letter ISO code the backend expects (RuneLength == 2).
export const countryOptions: SelectOption[] = [
  { value: "AF", label: "Afghanistan" },
  { value: "AX", label: "Åland Islands" },
  { value: "AL", label: "Albania" },
  { value: "DZ", label: "Algeria" },
  { value: "AS", label: "American Samoa" },
  { value: "AD", label: "Andorra" },
  { value: "AO", label: "Angola" },
  { value: "AI", label: "Anguilla" },
  { value: "AQ", label: "Antarctica" },
  { value: "AG", label: "Antigua and Barbuda" },
  { value: "AR", label: "Argentina" },
  { value: "AM", label: "Armenia" },
  { value: "AW", label: "Aruba" },
  { value: "AU", label: "Australia" },
  { value: "AT", label: "Austria" },
  { value: "AZ", label: "Azerbaijan" },
  { value: "BS", label: "Bahamas" },
  { value: "BH", label: "Bahrain" },
  { value: "BD", label: "Bangladesh" },
  { value: "BB", label: "Barbados" },
  { value: "BY", label: "Belarus" },
  { value: "BE", label: "Belgium" },
  { value: "BZ", label: "Belize" },
  { value: "BJ", label: "Benin" },
  { value: "BM", label: "Bermuda" },
  { value: "BT", label: "Bhutan" },
  { value: "BO", label: "Bolivia" },
  { value: "BQ", label: "Bonaire, Sint Eustatius and Saba" },
  { value: "BA", label: "Bosnia and Herzegovina" },
  { value: "BW", label: "Botswana" },
  { value: "BV", label: "Bouvet Island" },
  { value: "BR", label: "Brazil" },
  { value: "IO", label: "British Indian Ocean Territory" },
  { value: "BN", label: "Brunei Darussalam" },
  { value: "BG", label: "Bulgaria" },
  { value: "BF", label: "Burkina Faso" },
  { value: "BI", label: "Burundi" },
  { value: "CV", label: "Cabo Verde" },
  { value: "KH", label: "Cambodia" },
  { value: "CM", label: "Cameroon" },
  { value: "CA", label: "Canada" },
  { value: "KY", label: "Cayman Islands" },
  { value: "CF", label: "Central African Republic" },
  { value: "TD", label: "Chad" },
  { value: "CL", label: "Chile" },
  { value: "CN", label: "China" },
  { value: "CX", label: "Christmas Island" },
  { value: "CC", label: "Cocos (Keeling) Islands" },
  { value: "CO", label: "Colombia" },
  { value: "KM", label: "Comoros" },
  { value: "CG", label: "Congo" },
  { value: "CD", label: "Congo, Democratic Republic of the" },
  { value: "CK", label: "Cook Islands" },
  { value: "CR", label: "Costa Rica" },
  { value: "CI", label: "Côte d'Ivoire" },
  { value: "HR", label: "Croatia" },
  { value: "CU", label: "Cuba" },
  { value: "CW", label: "Curaçao" },
  { value: "CY", label: "Cyprus" },
  { value: "CZ", label: "Czechia" },
  { value: "DK", label: "Denmark" },
  { value: "DJ", label: "Djibouti" },
  { value: "DM", label: "Dominica" },
  { value: "DO", label: "Dominican Republic" },
  { value: "EC", label: "Ecuador" },
  { value: "EG", label: "Egypt" },
  { value: "SV", label: "El Salvador" },
  { value: "GQ", label: "Equatorial Guinea" },
  { value: "ER", label: "Eritrea" },
  { value: "EE", label: "Estonia" },
  { value: "SZ", label: "Eswatini" },
  { value: "ET", label: "Ethiopia" },
  { value: "FK", label: "Falkland Islands (Malvinas)" },
  { value: "FO", label: "Faroe Islands" },
  { value: "FJ", label: "Fiji" },
  { value: "FI", label: "Finland" },
  { value: "FR", label: "France" },
  { value: "GF", label: "French Guiana" },
  { value: "PF", label: "French Polynesia" },
  { value: "TF", label: "French Southern Territories" },
  { value: "GA", label: "Gabon" },
  { value: "GM", label: "Gambia" },
  { value: "GE", label: "Georgia" },
  { value: "DE", label: "Germany" },
  { value: "GH", label: "Ghana" },
  { value: "GI", label: "Gibraltar" },
  { value: "GR", label: "Greece" },
  { value: "GL", label: "Greenland" },
  { value: "GD", label: "Grenada" },
  { value: "GP", label: "Guadeloupe" },
  { value: "GU", label: "Guam" },
  { value: "GT", label: "Guatemala" },
  { value: "GG", label: "Guernsey" },
  { value: "GN", label: "Guinea" },
  { value: "GW", label: "Guinea-Bissau" },
  { value: "GY", label: "Guyana" },
  { value: "HT", label: "Haiti" },
  { value: "HM", label: "Heard Island and McDonald Islands" },
  { value: "VA", label: "Holy See" },
  { value: "HN", label: "Honduras" },
  { value: "HK", label: "Hong Kong" },
  { value: "HU", label: "Hungary" },
  { value: "IS", label: "Iceland" },
  { value: "IN", label: "India" },
  { value: "ID", label: "Indonesia" },
  { value: "IR", label: "Iran" },
  { value: "IQ", label: "Iraq" },
  { value: "IE", label: "Ireland" },
  { value: "IM", label: "Isle of Man" },
  { value: "IL", label: "Israel" },
  { value: "IT", label: "Italy" },
  { value: "JM", label: "Jamaica" },
  { value: "JP", label: "Japan" },
  { value: "JE", label: "Jersey" },
  { value: "JO", label: "Jordan" },
  { value: "KZ", label: "Kazakhstan" },
  { value: "KE", label: "Kenya" },
  { value: "KI", label: "Kiribati" },
  { value: "KP", label: "Korea, Democratic People's Republic of" },
  { value: "KR", label: "Korea, Republic of (South Korea)" },
  { value: "KW", label: "Kuwait" },
  { value: "KG", label: "Kyrgyzstan" },
  { value: "LA", label: "Lao People's Democratic Republic" },
  { value: "LV", label: "Latvia" },
  { value: "LB", label: "Lebanon" },
  { value: "LS", label: "Lesotho" },
  { value: "LR", label: "Liberia" },
  { value: "LY", label: "Libya" },
  { value: "LI", label: "Liechtenstein" },
  { value: "LT", label: "Lithuania" },
  { value: "LU", label: "Luxembourg" },
  { value: "MO", label: "Macao" },
  { value: "MG", label: "Madagascar" },
  { value: "MW", label: "Malawi" },
  { value: "MY", label: "Malaysia" },
  { value: "MV", label: "Maldives" },
  { value: "ML", label: "Mali" },
  { value: "MT", label: "Malta" },
  { value: "MH", label: "Marshall Islands" },
  { value: "MQ", label: "Martinique" },
  { value: "MR", label: "Mauritania" },
  { value: "MU", label: "Mauritius" },
  { value: "YT", label: "Mayotte" },
  { value: "MX", label: "Mexico" },
  { value: "FM", label: "Micronesia, Federated States of" },
  { value: "MD", label: "Moldova" },
  { value: "MC", label: "Monaco" },
  { value: "MN", label: "Mongolia" },
  { value: "ME", label: "Montenegro" },
  { value: "MS", label: "Montserrat" },
  { value: "MA", label: "Morocco" },
  { value: "MZ", label: "Mozambique" },
  { value: "MM", label: "Myanmar" },
  { value: "NA", label: "Namibia" },
  { value: "NR", label: "Nauru" },
  { value: "NP", label: "Nepal" },
  { value: "NL", label: "Netherlands" },
  { value: "NC", label: "New Caledonia" },
  { value: "NZ", label: "New Zealand" },
  { value: "NI", label: "Nicaragua" },
  { value: "NE", label: "Niger" },
  { value: "NG", label: "Nigeria" },
  { value: "NU", label: "Niue" },
  { value: "NF", label: "Norfolk Island" },
  { value: "MK", label: "North Macedonia" },
  { value: "MP", label: "Northern Mariana Islands" },
  { value: "NO", label: "Norway" },
  { value: "OM", label: "Oman" },
  { value: "PK", label: "Pakistan" },
  { value: "PW", label: "Palau" },
  { value: "PS", label: "Palestine, State of" },
  { value: "PA", label: "Panama" },
  { value: "PG", label: "Papua New Guinea" },
  { value: "PY", label: "Paraguay" },
  { value: "PE", label: "Peru" },
  { value: "PH", label: "Philippines" },
  { value: "PN", label: "Pitcairn" },
  { value: "PL", label: "Poland" },
  { value: "PT", label: "Portugal" },
  { value: "PR", label: "Puerto Rico" },
  { value: "QA", label: "Qatar" },
  { value: "RE", label: "Réunion" },
  { value: "RO", label: "Romania" },
  { value: "RU", label: "Russian Federation" },
  { value: "RW", label: "Rwanda" },
  { value: "BL", label: "Saint Barthélemy" },
  { value: "SH", label: "Saint Helena, Ascension and Tristan da Cunha" },
  { value: "KN", label: "Saint Kitts and Nevis" },
  { value: "LC", label: "Saint Lucia" },
  { value: "MF", label: "Saint Martin (French part)" },
  { value: "PM", label: "Saint Pierre and Miquelon" },
  { value: "VC", label: "Saint Vincent and the Grenadines" },
  { value: "WS", label: "Samoa" },
  { value: "SM", label: "San Marino" },
  { value: "ST", label: "Sao Tome and Principe" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "SN", label: "Senegal" },
  { value: "RS", label: "Serbia" },
  { value: "SC", label: "Seychelles" },
  { value: "SL", label: "Sierra Leone" },
  { value: "SG", label: "Singapore" },
  { value: "SX", label: "Sint Maarten (Dutch part)" },
  { value: "SK", label: "Slovakia" },
  { value: "SI", label: "Slovenia" },
  { value: "SB", label: "Solomon Islands" },
  { value: "SO", label: "Somalia" },
  { value: "ZA", label: "South Africa" },
  { value: "GS", label: "South Georgia and the South Sandwich Islands" },
  { value: "SS", label: "South Sudan" },
  { value: "ES", label: "Spain" },
  { value: "LK", label: "Sri Lanka" },
  { value: "SD", label: "Sudan" },
  { value: "SR", label: "Suriname" },
  { value: "SJ", label: "Svalbard and Jan Mayen" },
  { value: "SE", label: "Sweden" },
  { value: "CH", label: "Switzerland" },
  { value: "SY", label: "Syrian Arab Republic" },
  { value: "TW", label: "Taiwan" },
  { value: "TJ", label: "Tajikistan" },
  { value: "TZ", label: "Tanzania" },
  { value: "TH", label: "Thailand" },
  { value: "TL", label: "Timor-Leste" },
  { value: "TG", label: "Togo" },
  { value: "TK", label: "Tokelau" },
  { value: "TO", label: "Tonga" },
  { value: "TT", label: "Trinidad and Tobago" },
  { value: "TN", label: "Tunisia" },
  { value: "TR", label: "Türkiye" },
  { value: "TM", label: "Turkmenistan" },
  { value: "TC", label: "Turks and Caicos Islands" },
  { value: "TV", label: "Tuvalu" },
  { value: "UG", label: "Uganda" },
  { value: "UA", label: "Ukraine" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "GB", label: "United Kingdom" },
  { value: "US", label: "United States" },
  { value: "UM", label: "United States Minor Outlying Islands" },
  { value: "UY", label: "Uruguay" },
  { value: "UZ", label: "Uzbekistan" },
  { value: "VU", label: "Vanuatu" },
  { value: "VE", label: "Venezuela" },
  { value: "VN", label: "Viet Nam" },
  { value: "VG", label: "Virgin Islands (British)" },
  { value: "VI", label: "Virgin Islands (U.S.)" },
  { value: "WF", label: "Wallis and Futuna" },
  { value: "EH", label: "Western Sahara" },
  { value: "YE", label: "Yemen" },
  { value: "ZM", label: "Zambia" },
  { value: "ZW", label: "Zimbabwe" },
]

// Timezone options sorted by UTC offset
export const timezoneOptions: SelectOption[] = [
  // UTC-12:00
  { value: "Pacific/Baker_Island", label: "(UTC-12:00) Baker Island Time" },

  // UTC-11:00
  { value: "Pacific/Midway", label: "(UTC-11:00) Samoa Standard Time (Midway)" },
  { value: "Pacific/Niue", label: "(UTC-11:00) Niue Time" },

  // UTC-10:00
  { value: "Pacific/Honolulu", label: "(UTC-10:00) Hawaii Standard Time (Honolulu)" },
  { value: "Pacific/Tahiti", label: "(UTC-10:00) Tahiti Time" },
  { value: "Pacific/Rarotonga", label: "(UTC-10:00) Cook Island Time" },

  // UTC-09:30
  { value: "Pacific/Marquesas", label: "(UTC-09:30) Marquesas Time" },

  // UTC-09:00
  { value: "America/Anchorage", label: "(UTC-09:00) Alaska Standard Time (Anchorage)" },
  { value: "America/Juneau", label: "(UTC-09:00) Alaska Standard Time (Juneau)" },
  { value: "Pacific/Gambier", label: "(UTC-09:00) Gambier Time" },

  // UTC-08:00
  { value: "America/Los_Angeles", label: "(UTC-08:00) Pacific Standard Time (Los Angeles)" },
  { value: "America/Vancouver", label: "(UTC-08:00) Pacific Standard Time (Vancouver)" },
  { value: "America/Tijuana", label: "(UTC-08:00) Pacific Standard Time (Tijuana)" },
  { value: "America/Seattle", label: "(UTC-08:00) Pacific Standard Time (Seattle)" },
  { value: "America/San_Francisco", label: "(UTC-08:00) Pacific Standard Time (San Francisco)" },

  // UTC-07:00
  { value: "America/Denver", label: "(UTC-07:00) Mountain Standard Time (Denver)" },
  { value: "America/Phoenix", label: "(UTC-07:00) Mountain Standard Time (Phoenix)" },
  { value: "America/Calgary", label: "(UTC-07:00) Mountain Standard Time (Calgary)" },
  { value: "America/Edmonton", label: "(UTC-07:00) Mountain Standard Time (Edmonton)" },
  { value: "America/Boise", label: "(UTC-07:00) Mountain Standard Time (Boise)" },

  // UTC-06:00
  { value: "America/Chicago", label: "(UTC-06:00) Central Standard Time (Chicago)" },
  { value: "America/Mexico_City", label: "(UTC-06:00) Central Standard Time (Mexico City)" },
  { value: "America/Winnipeg", label: "(UTC-06:00) Central Standard Time (Winnipeg)" },
  { value: "America/Guatemala", label: "(UTC-06:00) Central Standard Time (Guatemala)" },
  { value: "America/Belize", label: "(UTC-06:00) Central Standard Time (Belize)" },
  { value: "America/Costa_Rica", label: "(UTC-06:00) Central Standard Time (Costa Rica)" },

  // UTC-05:00
  { value: "America/New_York", label: "(UTC-05:00) Eastern Standard Time (New York)" },
  { value: "America/Toronto", label: "(UTC-05:00) Eastern Standard Time (Toronto)" },
  { value: "America/Montreal", label: "(UTC-05:00) Eastern Standard Time (Montreal)" },
  { value: "America/Detroit", label: "(UTC-05:00) Eastern Standard Time (Detroit)" },
  { value: "America/Indianapolis", label: "(UTC-05:00) Eastern Standard Time (Indianapolis)" },
  { value: "America/Louisville", label: "(UTC-05:00) Eastern Standard Time (Louisville)" },
  { value: "America/Cancun", label: "(UTC-05:00) Eastern Standard Time (Cancun)" },
  { value: "America/Panama", label: "(UTC-05:00) Eastern Standard Time (Panama)" },
  { value: "America/Bogota", label: "(UTC-05:00) Colombia Time (Bogotá)" },
  { value: "America/Lima", label: "(UTC-05:00) Peru Time (Lima)" },

  // UTC-04:00
  { value: "America/Halifax", label: "(UTC-04:00) Atlantic Standard Time (Halifax)" },
  { value: "America/Santiago", label: "(UTC-04:00) Chile Standard Time (Santiago)" },
  { value: "America/Caracas", label: "(UTC-04:00) Venezuela Time (Caracas)" },
  { value: "America/La_Paz", label: "(UTC-04:00) Bolivia Time (La Paz)" },
  { value: "America/Guyana", label: "(UTC-04:00) Guyana Time (Georgetown)" },
  { value: "Atlantic/Bermuda", label: "(UTC-04:00) Atlantic Standard Time (Bermuda)" },

  // UTC-03:30
  { value: "America/St_Johns", label: "(UTC-03:30) Newfoundland Standard Time (St. John's)" },

  // UTC-03:00
  { value: "America/Sao_Paulo", label: "(UTC-03:00) Brasília Time (São Paulo)" },
  { value: "America/Rio_de_Janeiro", label: "(UTC-03:00) Brasília Time (Rio de Janeiro)" },
  { value: "America/Argentina/Buenos_Aires", label: "(UTC-03:00) Argentina Time (Buenos Aires)" },
  { value: "America/Montevideo", label: "(UTC-03:00) Uruguay Time (Montevideo)" },
  { value: "America/Asuncion", label: "(UTC-03:00) Paraguay Time (Asunción)" },
  { value: "America/Paramaribo", label: "(UTC-03:00) Suriname Time (Paramaribo)" },
  { value: "Atlantic/Stanley", label: "(UTC-03:00) Falkland Islands Time" },

  // UTC-02:00
  { value: "Atlantic/South_Georgia", label: "(UTC-02:00) South Georgia Time" },
  { value: "America/Noronha", label: "(UTC-02:00) Fernando de Noronha Time" },

  // UTC-01:00
  { value: "Atlantic/Azores", label: "(UTC-01:00) Azores Time" },
  { value: "Atlantic/Cape_Verde", label: "(UTC-01:00) Cape Verde Time" },

  // UTC+00:00
  { value: "UTC", label: "(UTC+00:00) Coordinated Universal Time" },
  { value: "Europe/London", label: "(UTC+00:00) Greenwich Mean Time (London)" },
  { value: "Europe/Dublin", label: "(UTC+00:00) Greenwich Mean Time (Dublin)" },
  { value: "Europe/Lisbon", label: "(UTC+00:00) Western European Time (Lisbon)" },
  { value: "Atlantic/Reykjavik", label: "(UTC+00:00) Greenwich Mean Time (Reykjavik)" },
  { value: "Africa/Accra", label: "(UTC+00:00) Greenwich Mean Time (Accra)" },
  { value: "Africa/Dakar", label: "(UTC+00:00) Greenwich Mean Time (Dakar)" },
  { value: "Africa/Abidjan", label: "(UTC+00:00) Greenwich Mean Time (Abidjan)" },

  // UTC+01:00
  { value: "Europe/Paris", label: "(UTC+01:00) Central European Time (Paris)" },
  { value: "Europe/Berlin", label: "(UTC+01:00) Central European Time (Berlin)" },
  { value: "Europe/Rome", label: "(UTC+01:00) Central European Time (Rome)" },
  { value: "Europe/Madrid", label: "(UTC+01:00) Central European Time (Madrid)" },
  { value: "Europe/Amsterdam", label: "(UTC+01:00) Central European Time (Amsterdam)" },
  { value: "Europe/Brussels", label: "(UTC+01:00) Central European Time (Brussels)" },
  { value: "Europe/Zurich", label: "(UTC+01:00) Central European Time (Zurich)" },
  { value: "Europe/Vienna", label: "(UTC+01:00) Central European Time (Vienna)" },
  { value: "Europe/Stockholm", label: "(UTC+01:00) Central European Time (Stockholm)" },
  { value: "Europe/Oslo", label: "(UTC+01:00) Central European Time (Oslo)" },
  { value: "Europe/Copenhagen", label: "(UTC+01:00) Central European Time (Copenhagen)" },
  { value: "Europe/Warsaw", label: "(UTC+01:00) Central European Time (Warsaw)" },
  { value: "Europe/Prague", label: "(UTC+01:00) Central European Time (Prague)" },
  { value: "Europe/Budapest", label: "(UTC+01:00) Central European Time (Budapest)" },
  { value: "Europe/Belgrade", label: "(UTC+01:00) Central European Time (Belgrade)" },
  { value: "Europe/Zagreb", label: "(UTC+01:00) Central European Time (Zagreb)" },
  { value: "Europe/Ljubljana", label: "(UTC+01:00) Central European Time (Ljubljana)" },
  { value: "Europe/Bratislava", label: "(UTC+01:00) Central European Time (Bratislava)" },
  { value: "Africa/Lagos", label: "(UTC+01:00) West Africa Time (Lagos)" },
  { value: "Africa/Casablanca", label: "(UTC+01:00) Western European Time (Casablanca)" },
  { value: "Africa/Algiers", label: "(UTC+01:00) Central European Time (Algiers)" },
  { value: "Africa/Tunis", label: "(UTC+01:00) Central European Time (Tunis)" },

  // UTC+02:00
  { value: "Europe/Helsinki", label: "(UTC+02:00) Eastern European Time (Helsinki)" },
  { value: "Europe/Bucharest", label: "(UTC+02:00) Eastern European Time (Bucharest)" },
  { value: "Europe/Athens", label: "(UTC+02:00) Eastern European Time (Athens)" },
  { value: "Europe/Sofia", label: "(UTC+02:00) Eastern European Time (Sofia)" },
  { value: "Europe/Riga", label: "(UTC+02:00) Eastern European Time (Riga)" },
  { value: "Europe/Tallinn", label: "(UTC+02:00) Eastern European Time (Tallinn)" },
  { value: "Europe/Vilnius", label: "(UTC+02:00) Eastern European Time (Vilnius)" },
  { value: "Europe/Kiev", label: "(UTC+02:00) Eastern European Time (Kiev)" },
  { value: "Asia/Jerusalem", label: "(UTC+02:00) Israel Standard Time (Jerusalem)" },
  { value: "Asia/Beirut", label: "(UTC+02:00) Eastern European Time (Beirut)" },
  { value: "Asia/Damascus", label: "(UTC+02:00) Eastern European Time (Damascus)" },
  { value: "Africa/Johannesburg", label: "(UTC+02:00) South Africa Standard Time (Johannesburg)" },
  { value: "Africa/Cape_Town", label: "(UTC+02:00) South Africa Standard Time (Cape Town)" },
  { value: "Africa/Cairo", label: "(UTC+02:00) Eastern European Time (Cairo)" },
  { value: "Africa/Khartoum", label: "(UTC+02:00) Central Africa Time (Khartoum)" },

  // UTC+03:00
  { value: "Europe/Istanbul", label: "(UTC+03:00) Turkey Time (Istanbul)" },
  { value: "Europe/Moscow", label: "(UTC+03:00) Moscow Standard Time (Moscow)" },
  { value: "Europe/Minsk", label: "(UTC+03:00) Moscow Standard Time (Minsk)" },
  { value: "Asia/Riyadh", label: "(UTC+03:00) Arabia Standard Time (Riyadh)" },
  { value: "Asia/Kuwait", label: "(UTC+03:00) Arabia Standard Time (Kuwait)" },
  { value: "Asia/Qatar", label: "(UTC+03:00) Arabia Standard Time (Qatar)" },
  { value: "Asia/Bahrain", label: "(UTC+03:00) Arabia Standard Time (Bahrain)" },
  { value: "Asia/Baghdad", label: "(UTC+03:00) Arabia Standard Time (Baghdad)" },
  { value: "Africa/Nairobi", label: "(UTC+03:00) East Africa Time (Nairobi)" },
  { value: "Africa/Addis_Ababa", label: "(UTC+03:00) East Africa Time (Addis Ababa)" },
  { value: "Africa/Dar_es_Salaam", label: "(UTC+03:00) East Africa Time (Dar es Salaam)" },
  { value: "Africa/Kampala", label: "(UTC+03:00) East Africa Time (Kampala)" },
  

  // UTC+03:30
  { value: "Asia/Tehran", label: "(UTC+03:30) Iran Standard Time (Tehran)" },

  // UTC+04:00
  { value: "Asia/Dubai", label: "(UTC+04:00) Gulf Standard Time (Dubai)" },
  { value: "Asia/Muscat", label: "(UTC+04:00) Gulf Standard Time (Muscat)" },
  { value: "Asia/Baku", label: "(UTC+04:00) Azerbaijan Time (Baku)" },
  { value: "Asia/Tbilisi", label: "(UTC+04:00) Georgia Time (Tbilisi)" },
  { value: "Asia/Yerevan", label: "(UTC+04:00) Armenia Time (Yerevan)" },

  // UTC+04:30
  { value: "Asia/Kabul", label: "(UTC+04:30) Afghanistan Time (Kabul)" },

  // UTC+05:00
  { value: "Asia/Karachi", label: "(UTC+05:00) Pakistan Standard Time (Karachi)" },
  { value: "Asia/Tashkent", label: "(UTC+05:00) Uzbekistan Time (Tashkent)" },
  { value: "Asia/Dushanbe", label: "(UTC+05:00) Tajikistan Time (Dushanbe)" },
  { value: "Asia/Ashgabat", label: "(UTC+05:00) Turkmenistan Time (Ashgabat)" },
  { value: "Asia/Samarkand", label: "(UTC+05:00) Uzbekistan Time (Samarkand)" },

  // UTC+05:30
  { value: "Asia/Kolkata", label: "(UTC+05:30) India Standard Time (Mumbai/Delhi)" },
  { value: "Asia/Colombo", label: "(UTC+05:30) India Standard Time (Colombo)" },

  // UTC+05:45
  { value: "Asia/Kathmandu", label: "(UTC+05:45) Nepal Time (Kathmandu)" },

  // UTC+06:00
  { value: "Asia/Dhaka", label: "(UTC+06:00) Bangladesh Standard Time (Dhaka)" },
  { value: "Asia/Almaty", label: "(UTC+06:00) Kazakhstan Time (Almaty)" },
  { value: "Asia/Bishkek", label: "(UTC+06:00) Kyrgyzstan Time (Bishkek)" },
  { value: "Asia/Thimphu", label: "(UTC+06:00) Bhutan Time (Thimphu)" },

  // UTC+06:30
  { value: "Asia/Yangon", label: "(UTC+06:30) Myanmar Time (Yangon)" },
  { value: "Indian/Cocos", label: "(UTC+06:30) Cocos Islands Time" },

  // UTC+07:00
  { value: "Asia/Bangkok", label: "(UTC+07:00) Indochina Time (Bangkok)" },
  { value: "Asia/Ho_Chi_Minh", label: "(UTC+07:00) Indochina Time (Ho Chi Minh City)" },
  { value: "Asia/Jakarta", label: "(UTC+07:00) Western Indonesia Time (Jakarta)" },
  { value: "Asia/Phnom_Penh", label: "(UTC+07:00) Indochina Time (Phnom Penh)" },
  { value: "Asia/Vientiane", label: "(UTC+07:00) Indochina Time (Vientiane)" },

  // UTC+08:00
  { value: "Asia/Shanghai", label: "(UTC+08:00) China Standard Time (Shanghai/Beijing)" },
  { value: "Asia/Hong_Kong", label: "(UTC+08:00) Hong Kong Time (Hong Kong)" },
  { value: "Asia/Taipei", label: "(UTC+08:00) China Standard Time (Taipei)" },
  { value: "Asia/Singapore", label: "(UTC+08:00) Singapore Standard Time (Singapore)" },
  { value: "Asia/Kuala_Lumpur", label: "(UTC+08:00) Malaysia Time (Kuala Lumpur)" },
  { value: "Asia/Manila", label: "(UTC+08:00) Philippine Standard Time (Manila)" },
  { value: "Asia/Brunei", label: "(UTC+08:00) Brunei Time (Bandar Seri Begawan)" },
  { value: "Asia/Ulaanbaatar", label: "(UTC+08:00) Mongolia Time (Ulaanbaatar)" },
  { value: "Australia/Perth", label: "(UTC+08:00) Australian Western Standard Time (Perth)" },
  

  // UTC+09:00
  { value: "Asia/Tokyo", label: "(UTC+09:00) Japan Standard Time (Tokyo)" },
  { value: "Asia/Seoul", label: "(UTC+09:00) Korea Standard Time (Seoul)" },
  { value: "Asia/Pyongyang", label: "(UTC+09:00) Korea Standard Time (Pyongyang)" },
  { value: "Pacific/Palau", label: "(UTC+09:00) Palau Time" },

  // UTC+09:30
  { value: "Australia/Adelaide", label: "(UTC+09:30) Australian Central Standard Time (Adelaide)" },
  { value: "Australia/Darwin", label: "(UTC+09:30) Australian Central Standard Time (Darwin)" },

  // UTC+10:00
  { value: "Australia/Sydney", label: "(UTC+10:00) Australian Eastern Standard Time (Sydney)" },
  { value: "Australia/Melbourne", label: "(UTC+10:00) Australian Eastern Standard Time (Melbourne)" },
  { value: "Australia/Brisbane", label: "(UTC+10:00) Australian Eastern Standard Time (Brisbane)" },
  { value: "Australia/Hobart", label: "(UTC+10:00) Australian Eastern Standard Time (Hobart)" },
  { value: "Australia/Canberra", label: "(UTC+10:00) Australian Eastern Standard Time (Canberra)" },
  { value: "Pacific/Guam", label: "(UTC+10:00) Chamorro Standard Time (Guam)" },
  { value: "Pacific/Port_Moresby", label: "(UTC+10:00) Papua New Guinea Time (Port Moresby)" },
  { value: "Pacific/Chuuk", label: "(UTC+10:00) Chuuk Time" },

  // UTC+10:30
  { value: "Australia/Lord_Howe", label: "(UTC+10:30) Lord Howe Standard Time" },

  // UTC+11:00
  { value: "Pacific/Noumea", label: "(UTC+11:00) New Caledonia Time" },
  { value: "Pacific/Pohnpei", label: "(UTC+11:00) Pohnpei Standard Time" },
  { value: "Pacific/Kosrae", label: "(UTC+11:00) Kosrae Time" },
  { value: "Pacific/Norfolk", label: "(UTC+11:00) Norfolk Island Time" },

  // UTC+12:00
  { value: "Pacific/Auckland", label: "(UTC+12:00) New Zealand Standard Time (Auckland)" },
  { value: "Pacific/Wellington", label: "(UTC+12:00) New Zealand Standard Time (Wellington)" },
  { value: "Pacific/Fiji", label: "(UTC+12:00) Fiji Time (Suva)" },
  { value: "Pacific/Tarawa", label: "(UTC+12:00) Gilbert Island Time" },
  { value: "Pacific/Majuro", label: "(UTC+12:00) Marshall Islands Time" },
  { value: "Pacific/Nauru", label: "(UTC+12:00) Nauru Time" },
  { value: "Pacific/Tuvalu", label: "(UTC+12:00) Tuvalu Time" },
  { value: "Pacific/Wake", label: "(UTC+12:00) Wake Island Time" },
  { value: "Pacific/Wallis", label: "(UTC+12:00) Wallis & Futuna Time" },

  // UTC+12:45
  { value: "Pacific/Chatham", label: "(UTC+12:45) Chatham Standard Time" },

  // UTC+13:00
  { value: "Pacific/Tongatapu", label: "(UTC+13:00) Tonga Time" },
  { value: "Pacific/Apia", label: "(UTC+13:00) Samoa Standard Time" },
  { value: "Pacific/Enderbury", label: "(UTC+13:00) Phoenix Island Time" },
  { value: "Pacific/Fakaofo", label: "(UTC+13:00) Tokelau Time" },

  // UTC+14:00
  { value: "Pacific/Kiritimati", label: "(UTC+14:00) Line Islands Time" }
]

// Language options - Currently only US English is available
// Language options (BCP-47). Intentionally limited to English for now;
// add more entries here as localisation lands — every consumer picks them up.
export const languageOptions: SelectOption[] = [
  { value: "en-US", label: "English" },
]
